stages:
  prepare:
    cmd: python3 scripts/create_reddit_dataset.py
    # deps:
    params:
      - prepare.max_examples
      - prepare.curated_subreddits
      - prepare.random_seed
      - prepare.sample_size_test
      - prepare.n_most_common_words
      - prepare.sample_size_train
    outs:
      - data/reddit/reddit_dataset_1300.pkl
      - data/reddit/most_common_words.pkl
  zmap:
    cmd: python3 scripts/zmap.py
    deps:
      - data/reddit/reddit_dataset_1300.pkl
      - data/reddit/most_common_words.pkl
    params:
      - zmap.kwords
      - zmap.alpha
    metrics:
      - results/accuracy.json:
          cache: false
    plots:
      - results/confusion_plot.csv:
          cache: false
    #outs:
      #- data/maps/Zmap_20k_w2v_words_alpha0.pt


    