# params.yaml

#random_seed: 42

prepare:
  random_seed: 41
  max_examples: 20000
  n_most_common_words: 10
  sample_size_test: 1300
  sample_size_train: 15
  curated_subreddits: ['relationships', 'trees', 'gaming', 'funny', 'politics', 'sex', 'Fitness', 'worldnews', 'personalfinance', 'technology']
zmap:
  kwords: 2000
  alpha: 5